namespace Json_watcher
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Button btnSelectFile;
        private System.Windows.Forms.TextBox textDisplayWindow;
        private System.Windows.Forms.Button btnToggleTheme;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Autogenerated codes
        // Windows Form Designer generated code
        private void InitializeComponent()
        {
            btnSelectFile = new Button();
            textDisplayWindow = new TextBox();
            btnToggleTheme = new Button();
            SuspendLayout();
            // 
            // btnSelectFile
            // 
            btnSelectFile.Location = new Point(12, 12);
            btnSelectFile.Name = "btnSelectFile";
            btnSelectFile.Size = new Size(100, 23);
            btnSelectFile.TabIndex = 0;
            btnSelectFile.Text = "Select JSON File";
            btnSelectFile.UseVisualStyleBackColor = true;
            btnSelectFile.Click += BtnSelectFile_Click;
            // 
            // textDisplayWindow
            // 
            textDisplayWindow.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            textDisplayWindow.Location = new Point(12, 41);
            textDisplayWindow.Multiline = true;
            textDisplayWindow.Name = "textDisplayWindow";
            textDisplayWindow.ScrollBars = ScrollBars.Vertical;
            textDisplayWindow.Size = new Size(760, 397);
            textDisplayWindow.TabIndex = 1;
            // 
            // btnToggleTheme
            // 
            btnToggleTheme.Location = new Point(118, 12);
            btnToggleTheme.Name = "btnToggleTheme";
            btnToggleTheme.Size = new Size(100, 23);
            btnToggleTheme.TabIndex = 2;
            btnToggleTheme.Text = "Toggle Theme";
            btnToggleTheme.UseVisualStyleBackColor = true;
            btnToggleTheme.Click += BtnToggleTheme_Click;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(784, 461);
            Controls.Add(textDisplayWindow);
            Controls.Add(btnSelectFile);
            Controls.Add(btnToggleTheme);
            Name = "Form1";
            Text = "JSON File Monitor";
            ResumeLayout(false);
            PerformLayout();
        }
        #endregion

    }
}
